[build]
  command = "cd frontend && npm run build"
  publish = "frontend/.next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_BACKEND_URL = ""
